image: marketsquare/robotframework-browser
include:
  - local: /.gitlab/ci/extends.yml

stages:
  - install
  - smoke_test
  - regression_test

install_dependencies:
  stage: install
  extends:
    - .install:api
  script:
    - python3 --version

smoke_test:
  stage: smoke_test
  extends:
    - .install:api
    - .robot_test_template
  variables:
    TEST_PATH: ./tests
    TEST_TAG: Smoke

regression_test:
  stage: regression_test
  extends:
    - .install:api
    - .robot_test_template
  variables:
    TEST_PATH: ./tests
    TEST_TAG: Regression
