image: python:3.8
include:
  - local: /.gitlab/ci/extends.yml

stages:
  - install
  - test

install_dependencies:
  stage: install
  extends:
    - .install:api
  script:
    - python3 --version

run_tests:
  stage: test
  extends:
    - .install:api
  script:
    - robot --outputdir results ./TestSuites
  artifacts:
    paths:
      - results/
    expire_in: 1 day
  dependencies:
    - install_dependencies
