image: marketsquare/robotframework-browser
include:
  - local: /.gitlab/ci/extends.yml

stages:
  - install 🛠️
  - smoke_test 🚬
  - regression_test 📊
  - notify 🚩

install_dependencies:
  stage: install 🛠️
  extends:
    - .install:api
  script:
    - python3 --version

smoke_test:
  stage: smoke_test 🚬
  extends:
    - .install:api
    - .robot_test_template
  variables:
    TEST_PATH: ./tests
    TEST_TAG: Smoke

regression_test:
  stage: regression_test 📊
  extends:
    - .install:api
    - .robot_test_template
  variables:
    TEST_PATH: ./tests
    TEST_TAG: Regression

notify_slack_on_failure:
  stage: notify 🚩
  script:
    - 'curl -X POST --data-urlencode "payload={\"channel\": \"#test-web\", \"username\": \"DAXme Test\", \"text\": \":x: Pipeline FAILED during stage *$CI_JOB_STAGE* on project *$CI_PROJECT_NAME* (branch *$CI_COMMIT_REF_NAME*). <$CI_PIPELINE_URL|View Pipeline>\", \"icon_emoji\": \":ghost:\"}" $SLACK_WEBHOOK_URL'
  when: on_failure
  only:
    refs:
      - dev
      - master
